# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gh-not
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc

release:
  draft: true
